```{r load_libs, echo=FALSE, message=FALSE, warning=FALSE}
# clean environment
rm(list = ls())  
# load packages
library(sf)
library(tidyverse)
library(skimr)
library(tidymodels)
```

```{r load_data, echo=FALSE, message=FALSE, warning=FALSE}
# Shetland BBS
survey_BBS_2002_2018     <- st_read("/Users/anthony/Documents/GitHub/Waders/data/Shetland_BBS/BBSgrid2002_2018.dbf", quiet=T)

```


# Results

<!-- Exploratory Data Analysis
child doc is loaded in-line -->
```{r child='results_child_docs/EDA.Rmd'}
```

##  Detectability

The `r` package `unmarked` was used to generate an estimate for the probability of detection, or *detectability*. Table \@ref(tab:detectabilityTab) shows the average *detectability* across all survey years, for each species.

```{r detectabilityTab, echo=FALSE, fig.cap='Average detectability of breeding wader species on Shetland 2002-2019', message=FALSE, warning=FALSE}
# Species detectability results
detect_df <- data.frame(
  # Waders under study
  Species = c("OC", "L", "RK", "CU", "SN"),
  d = c(0.803, # oystercatcher 
        0.723, # lapwing
        0.667, # redshank
        0.831, # curlew
        0.723 # snipe
        )) 
detect_df %>%
  # knit table
  knitr::kable(
    col.names = c("Species","Detectability"),
    booktabs = TRUE
  )
```

<!-- Improved grassland classification
child doc is loaded in-line -->
```{r child='results_child_docs/improved_grassland.Rmd'}
```

<!-- Environmental Covariate Analysis
child doc is loaded in-line -->
```{r child='results_child_docs/Env_covar_analysis.Rmd'}
```

<!-- Environmental Covariate Response
child doc is loaded in-line -->
```{r child='results_child_docs/Env_covar_response.Rmd'}
```

<!-- Information Theory Response
child doc is loaded in-line -->
```{r child='results_child_docs/IT_covar_response.Rmd'}
```

<!-- Abundance over time and spatial distribution
child doc is loaded in-line -->
```{r child='results_child_docs/wader_abundance.Rmd'}
```

<!-- Predict improve grassland and then work
out if strength of connectivity with wader breeder 
territories are significant -->
```{r eval=FALSE, child='results_child_docs/grassland_connectivity.Rmd', include=FALSE}
```




